### ISSUE TITLE
Compatibility issue with numpy 2.0

### ISSUE THREAD

**Issue by vik748** [matthew-brett/transforms3d#66]
The package doesn't seem to work with numpy 2.0, crashes with the following error:
```
>>> from transforms3d.euler import euler2quat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/transforms3d/__init__.py", line 10, in <module>
    from . import quaternions
  File "/usr/local/lib/python3.10/dist-packages/transforms3d/quaternions.py", line 26, in <module>
    _MAX_FLOAT = np.maximum_sctype(np.float64)
  File "/home/daps/.local/lib/python3.10/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.maximum_sctype` was removed in the NumPy 2.0 release. Use a specific dtype instead. You should avoid relying on any implicit mechanism and select the largest dtype of a kind explicitly in the code.
```

Appears to be due to a breaking change in Numpy's API.

**Comment by matthew-brett** [comment]
Thanks for the report.  I've just uploaded a new release.   Does it work?

**Comment by joshuacwnewton** [comment]
LGTM! (I'm not @vik748, but my project had encountered issues in our CI [overnight](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/9546561946/job/26309700294#step:3:1225), but retrying just now, there are [no such errors](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/9549915754/job/26320639602?pr=4533). We are getting different errors, but that's due to the _many_ upstream incompatibilities with `numpy==2.0.0`, aha.)

Thanks for being on top of this! :hearts:

**Comment by vik748** [comment]
Yep, after upgrading to version 0.4.2 with `pip install --upgrade transforms3d` the import works now.  Thanks for the quick turnaround.
